### ISSUE TITLE
Resolve flagged security issues.

### ISSUE THREAD

**Issue by Ringenberg** [CMUEberlyCenter/eberly-docuscope-wa#17]
See the security tab on the github repository site.

**Comment by Ringenberg** [comment]
6cf80850cfd89c3612677ffca2681afaf594906d resolves most of them by updating the requirements.txt file to reflect what is currently used in deployment as it directly uses pip to get the latest.  Moving to use pipenv for dependency maintenance would be advised as it greatly helps in generating reproducible environments.

**Comment by Ringenberg** [comment]
Many security issues are blocked because of the forced version lock of spacy=2.3.5 which requires python 3.7.
Python 3.7 entered end of life back in 2023.  This means that many of the libraries that work with python 3.7 are no longer maintained and woefully out of date.  Ideally, the spacy data files would be regenerated using spacy 3 and a live version of python so that this dependency could be broken.

**Comment by sugurui** [comment]
We should be able to use SpaCy 3.5. I've been using 3.5.3, with Python 3.11 for a while. We can use the "[en_core_web_sm](https://spacy.io/models)" (without any customizations we did in the past). 

I do not recall making any changes to document.py, but it's been a while some minor changes are necessary (some changes to method names etc.).
