### ISSUE TITLE
Text editor not editable unless the user click the top area

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#27]
The user/writer must click the top area of the text editor in order to start typing. Most users expect to click anywhere in the editor to start typing.

**Comment by Ringenberg** [comment]
This is an issue with the text editor library that is being used.  I believe we previously had it listed as a known low priority issue.

**Comment by Ringenberg** [comment]
Adding a click handler that forces focus on editor to background to see if that improves usability.
