### ISSUE TITLE
Content for Help > About should be changed

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#32]
Please update the text used for Help > About to the following:

DocuScope Write & Audit (citation) is an environment for structuring writing tasks through visualization. It includes panels for visualizing reader expectations and textual coherence. It has recently been updated to accommodate generative AI through a notes-to-prose feature.

**Comment by Ringenberg** [comment]
Using https://www.cmu.edu/corecompetencies/communication/resources-and-tools/docuscope/index.html for the citation for now.
