### ISSUE TITLE
Allow users to copy the expectations content

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#33]
This is a somewhat low priority feature request.

It's be ideal if we can allow the user to insert the content (outline or questions) of the expectation pane to the text editor.

The user may insert one expectation (or outline item) at a time; or they may insert the entire outline (with expectation questions).

**Comment by Ringenberg** [comment]
This requirement has been redefined to inserting full outline and currently works according to that requirement.
