### ISSUE TITLE
Use of the latest notes-to-prose prompt template

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#35]
It's not really an issue, but we can do more realistic testing of how writing multiple paragraphs or an essay can be written (i.e., a larger work flow) using the notes-to-prose tool once the **latest notes-to-prose prompt template is used** in the system.

**Comment by Ringenberg** [comment]
Templates are immediately available once a new rules/configuration json file is uploaded and selected in the instructor interface.
