### ISSUE TITLE
specify the temperature and system role settings

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#37]
I'm not sure if the temperature and the system's role are set in the current implementation, but the following settings seem to work well for the notes and prose feature.

**System’s role:** "Your are a writing assistant working for a content expert. Your primary task is to translate the expert's notes to a paragraph."

**Temperature:** 0.0

**Comment by Ringenberg** [comment]
40a2ad2bdb78ad76846a090bbbd16905837f7a52 adds ability to specify temperature and role in configuration file.
