### ISSUE TITLE
A.I. Scribe Warning Dialog Does not show at the launch time sometimes

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#39]
I'm not sure if it was intended behavior, but when I launched the pilot today, the AI Scribe Warning Dialog did not appear. I thought it did when I initially launched it.

Since it did not appear to start with, I thought it did remember my selection form 2 days ago; but it did not. I was wondering if the dialog should appear every time the app is launched (unless it can remember the selection).

**Comment by Ringenberg** [comment]
It is supposed to remember if you have seen the information dialog and opt-in setting within a session.  I have not been able to replicate this bug in particular but some minor improvements in the initialization and setting of the stored information should mitigate the issue.
