### ISSUE TITLE
Notes-2-Prose results in an error message

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#40]
When the user uses the **notes-2-prose** tool, it results in the following error message: "An error occurred while converting your notes to prose."

It looks like this issue started after the pilot app was updated to use the new format for expectations JSON file on Wed 18, 2023.

The following expectations files (upload to the canvas environment) were used to produce this error:

- Simon - Student Argument (v.2023.10.19).json
- Joel - Student Argument (v.2023.10.19).json
- Sharon - Student Report (v.2023.10.19).json

The problem may be in the JSON files.

**Comment by Ringenberg** [comment]
It looks like the code for converting string temperatures to numbers which is required in the openai call did not get properly implemented.

**Comment by Ringenberg** [comment]
Related to #37
