### ISSUE TITLE
Make the rules editor to generate rules files without the proprietary prompts.

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#48]
What we have been calling "rules" file (JSON file) contains the proprietary "Prompts". We will need to separate those prompts into a separate JSON file. The first step is for Suguru to revise the rules editor (now called Writing Task Definitions editor) so that it generates rules files without the prompts. The prompts are already in a separate JSON file.

**Comment by Ringenberg** [comment]
Backend is set up to load the templates server side and relies on the front end to provide the data necessary to instantiate the templates.  The templates should also now be better protected because they are never sent to the client.
