### ISSUE TITLE
Tools for the fall release

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#51]
Here is a proposed list of tools that we want to support in the fall release:

**Write:**
- Generate
  - Notes to Prose
  - Notes to Bullets
- Content
  - Check Expectation
  - [TBD]
- Flow
  - Logical Flow (this feature should only work for a selected text segment)
  - Term Matrix (i.e., OnTopic Visualization)
- Clarity
  - Sentence Density (Visualization)
  - Copy Edit (it's a low priority item if it requires significant time/effort).

Note: 

In general, tools under "Write" focus on supporting development of parts.

The visualization shown in "Term Matrix" and "Sentence Density" must be updated if the text in the editor is revised. Our suggestion is that as soon as the text is changed, we gray out these visualizations if they are visible, with a button saying something like "update visualization". If those visualizations are NOT visible, then the visualization is updated when the user requests for them. Will this work?

Dave and Suguru are still working on the 2nd tool under Content. It's expected to be similar to "Check Expectation" where AI will respond by one or two paragraphs.

----

**Review:**
- All Expectations
- Key Points
- Lines of Arguments
- Stance
- Organization

Note: All of these tools under **Review** are new, and their prompts are under development. These features assume that the text in fixed, so that sentences/paragraphs can be highlighted.

**Comment by Ringenberg** [comment]
New specification is:
* Generate
  * Prose
  * Bullets
  * Expectation
  * All Expectations
* Review (new window)
  * Key Ideas
  * Arguments
  * Sentences (onTopic)
  * Term Matrix (onTopic)
* Refine
  * Flow
  * Copy Edit

**Comment by Ringenberg** [comment]
Compete
