### ISSUE TITLE
Match the visual aspects of the UI to GoGo's New Design

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#62]
The attached PDF includes annotated screenshots for implementing GoGo's visual design for the UI. It does not contains all the details, but all the noticeable elements are included.

Some of GoGo's design choices are modified, and a few changes to address the current UI issues, which was uncovered during the testing, is also included in this document.

While this document focuses primary on cosmetic (i.e., visual issues), some interactive issues are included as well. We tried to include those interactive issues as separate GitHub issues as well.

[UI Comments (Aug 25, 2024).pdf](https://github.com/user-attachments/files/16743024/UI.Comments.Aug.25.2024.pdf)

**Comment by Ringenberg** [comment]
Most of issues have been resolved satisfactory.

Interface has deviated based on feedback from the cited interface to no longer consider it valid.
