### ISSUE TITLE
The Check Expectations UI flows under the Draft section is too flexible

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#63]
The UI for the Check Expectation works as expected if the user first selects a text segment, clicks the “Check” button, and then selects an expectation from the Writing Task dialog.

However, if the user clicks the “Cancel” button in the Writing Task dialog, then, the sidebar shows a button under the “Expectation”, which allows the user to select an expectation.

The expected UI behavior is to go back to the previous state (i.e., before the “Check” button is clicked) if the Cancel button is clicked. 

The only way to use the Check Expectation feature should be to select a text segment, click the “Check” button, and then select an expectation from the Writing Task dialog.

**Comment by Ringenberg** [comment]
Duplicate #81
