### ISSUE TITLE
The "Review" and the "All Expectations" windows should be in a new window (not just a new tab).

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#65]
Currently, if the user clicks the Review button, the Review window is opened in a new tab within the same window. The same is true for the All Expectations tool. 

These windows should be opened in a new (separate) window to allow the user to keep using the original Draft tool while referencing these new windows.

**Comment by Ringenberg** [comment]
I have done what I can, but this is behavior is set in the user's browser preferences.

**Comment by sugurui** [comment]
I thought window.open() would create a new window if windowFeatures, such as width and height, are specified.  I was wondering if this technique no longer works.
