### ISSUE TITLE
In the Review UI, the sentences that are associated with a selected item on the sidebar are not highlighted in the text editor.

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#68]
When an item in the results on the sidebar for the Lines of Arguments tool, the Key Ideas tool, and the Logical Progression Issues tool is selected, the sentences that are associated with the selected item should be highlighted in the editor.

**Comment by Ringenberg** [comment]
Additional feature of adding some space so target top is not necessarily at the top.
