### ISSUE TITLE
"low hanging fruit" cosmetic fixes (mostly)

### ISSUE THREAD

**Issue by sugurui** [CMUEberlyCenter/eberly-docuscope-wa#76]
Attached annotated screenshots show various cosmetic adjustments that are relatively easy to make. But, I’ve commented on a few things that may require extra time and/or non-cosmetic issues; so you may or may not address these depending on the effort level to address them.

The higher priority items are about spaces, dimensions and few colors. I did not provide exact sizes/dimensions but if you are not sure, please ask me or refer to the screenshots I provided earlier.

Comments on the visualizations are mostly low priority, but if it’s possible to (a) change the little circle smaller, and (b) reduce the font size of the text in the legend (to fit each label in a single line), that’d improve the look & feel.

I will also add this PDF to the GitHub Issues, so that you can track it.

[UI Comments (2024.09.20).pdf](https://github.com/user-attachments/files/17075867/UI.Comments.2024.09.20.pdf)

**Comment by Ringenberg** [comment]
Page 1 (initial)
- [ ] Tighten space in editor menu
- [ ] Vertically align outline title to editor menu
- [ ] Change tab highlighting
- [ ] make pop-out icon next to review smaller.
- [ ] Change button disable coloring.
- [ ] Remove button border
- [ ] Use single svg icon for "check all"
- [ ] Tighten space around tool buttons.
- [ ] Select outline button to width: 50%
Page 2 (initial)
- [ ] Remove frame from focused editor
- [ ] Change splitter gutter.
Page 3 (Review: Logical Progrssion)
- [ ] Remove frame around uneditable text.
- [ ] Menu dropdown to more closely resemble tool buttons in size and decorations.
- [ ] Fix spacing on Logical Progression Issues
- [ ] Smaller accordion rollup button.
- [ ] Open accordion should use highlight color
Page 4 (Review: Lines of Arguments)
- [ ] Adjust spacing around headings
- [ ] Eliminate accordion styling
Page 5 (Generate Prose)
- [ ] Remove User input box
- [ ] Make header smaller font, reduce margins.
- [ ] Use new ai response icon (without check)
- [ ] Use new clipboard icon
- [ ] Use secondary color button for view outline (C2D4EC)
- [ ] Smaller drawer icon.
Page 6 (term matrix)
- [ ] Uniform paragraph number button size.
- [ ] Tighten space between lines.
Page 7 (Sentence Density)
- [ ] Remove underlines
- [ ] slightly darker gray than light for paragraph separators.
- [ ] reduce gaps between cells.

**Comment by Ringenberg** [comment]
Focus frame around editor should not be removed for accessibility reasons: https://www.a11yproject.com/posts/never-remove-css-outlines/#:%7E:text=Using%20the%20CSS%20rule%20%3Afocus,with%20the%20link%20or%20control

**Comment by Ringenberg** [comment]
Underlining for sentence density should be used for sentence text view with parts of speech decorations.
![Screenshot 2024-09-23 102755](https://github.com/user-attachments/assets/12d3e4ee-21f1-4c30-beca-92712ff65e77)

**Comment by Ringenberg** [comment]
From 25Sept2024 meeting:

Term Matrix:
- [ ] Fix dot size to match legend
- [ ] Remove search
- [ ] Order by frequency
- [ ] Fix paragraph highlighting

**Comment by Ringenberg** [comment]
Most issues resolved satisfactorily.

Deviations due to feedback and additional features render most of this issue obsolete.
