### ISSUE TITLE
Occasionally, no text segments are highlighted when they should be.

### ISSUE THREAD

**Issue by Ringenberg** [CMUEberlyCenter/eberly-docuscope-wa#77]
Occasionally, no text segments (sentences) are highlighted in the editor when a specific AI feedback is selected by the user.

This problem has been observed in the Term matrix, Check all expectations, and Lines of argument.

**Comment by Ringenberg** [comment]
Catching more "none" responses should help this for All Expectations.

**Comment by Ringenberg** [comment]
Adding scrollIntoView should help address paragraph highlighting in Term Matrix.

**Comment by Ringenberg** [comment]
Some of the lack of highlighting is because there are no sentences listed in the LLM's response, though often appropriately in all cases that I have seen.

**Comment by sugurui** [comment]
The desktop prototype shows a warning icon when no sentences are listed in the LLM's response. Can we do the same?

We can try to improve the prompt, but it would be nice if we can handle this case in case we cannot prevent it 100%.
